name: Test

on:
  push:
    branches: ["main", "env/prod", "env/dev"]
  pull_request:
    types: ["opened", "synchronize"]

jobs:
  unit-test:
    name: Unit tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v3
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: npm install
      - name: Run Vitest
        run: npm run test