# import * from "./types/Member.gql"
# import * from "./types/ServerActivity.gql"
# import * from "./types/MainChannel.gql"
# import * from "./types/MainRole.gql"

# QUERY - for querying data (SELECT)

type Query {
  member(id: ID!): Member # Discord ID
  members: [Member]!

  todayServerActivity: ServerActivity!
  serverActivity(historyCount: Int!): [ServerActivity]!

  roles: [MainRole]
  channels: [MainChannel]
}

# MUTATION - for creating new and updating/deleting existing data (INSERT, UPDATE, DELETE)

type Mutation {
  createMember(
    id: ID!
    username: String!
    profilPicture: String!
    isOnServer: Boolean
  ): Member

  updateMember(id: ID!, input: MemberInput!): Boolean!

  incMemberDiscordVoiceMinute(id: ID!): Boolean!
  incMemberDiscordActivityChannel(id: ID!, channelId: ID!): Boolean!

  setServerActivityMemberCount(count: Int!): Boolean!

  addRole(roleId: ID!, category: String!): Boolean!
  removeRole(roleId: ID!): Boolean!

  addChannel(channelId: ID!, category: String!): Boolean!
  removeChannel(channelId: ID!): Boolean!
}
