scalar Date

## QUERY - for querying data (SELECT operations) ##

type Query {
    member(id: ID!): Member # Discord ID
    members: [Member]!

    todayServerActivity: ServerActivity!
    serverActivity(historyCount: Int!): [ServerActivity]!
}

## MUTATION - for creating new and updating/deleting existing data (INSERT, UPDATE, DELETE) ##

type Mutation {
    createMember(id: ID!, username: String!, profilPicture: String!, isOnServer: Boolean): Boolean! # false if member already exists
    updateMember(id: ID!, username: String, profilPicture: String, isOnServer: Boolean): Boolean! # false if member does not exist
}

## TYPES ## 

# Member

type Member {
    _id: String! # Discord ID

    username: String!
    profilPicture: String!

    isOnServer: Boolean!

    activity: DiscordActivity!
}

type DiscordActivity {
    voiceMinute: Int!
    messages: DiscordMessageActivity!
}

type DiscordMessageActivity {
    totalCount: Int!
    monthCount: Int!
    perChannel: [ChannelMessageCount]!
}

type ChannelMessageCount {
    channelId: String!
    messageCount: Int!
}

# ServerActivity

type ServerActivity {
    date: Date!

    voiceMinute: Int!
    messageCount: Int!
    memberCount: Int!
}