enum TierUpdate {
    UP
    NEUTRAL
    DOWN
}

# Types

type Member {
    _id: String! # Discord ID
    username: String!
    profilePicture: String!

    birthday: Date

    isOnServer: Boolean!

    activity: DiscordActivity!
}

type DiscordActivity {
    tier: Int!
    voiceMinute: Int!
    monthVoiceMinute: Int!
    messages: DiscordMessageActivity!
    points: ActivityPoints!
}

type ActivityPoints {
    count: Int!
    progress: TierUpdate!
}

type DiscordMessageActivity {
    totalCount: Int!
    monthCount: Int!
    perChannel: [ChannelMessageCount]!
}

type ChannelMessageCount {
    channelId: String!
    messageCount: Int!
}

# Inputs

input MemberInput {
    username: String
    profilePicture: String

    birthday: Date

    isOnServer: Boolean
}
